---
driver:
  name: terraform
  parallelism: 1

provisioner:
  name: terraform

verifier:
  name: awspec
  systems:
    - name: basic
      backend: local

platforms:
  - name: aws

suites:
  - name: default
    verifier:
      name: awspec
