#source 'https://rubygems.org/' do
#  gem 'awspec', '~> 1.17.4'
#  gem 'kitchen-terraform', '~> 5.0'
#  gem 'kitchen-verifier-awspec', '~> 0.2.0'
#end

ruby '2.4.2'

source 'https://rubygems.org/' do
  gem 'aws-sdk', '~> 3.0.1'
  gem 'awspec', '~> 1.4.0'
  gem 'kitchen-terraform', '~> 3.1'
  gem 'kitchen-verifier-awspec', '~> 0.1.1'
  gem 'rhcl', '~> 0.1.0'
end